### ISSUE TITLE
International data?

### ISSUE THREAD

**Issue by RoyalTS** [google-research/open-covid-19-data#158]
Will you also make the data available for regions outside of the US?

**Comment by RazvanZamfira** [comment]
Is the search data also available for regions outside the US?

**Comment by shekelto** [comment]
As mentioned in our [blogpost](https://blog.google/technology/health/using-symptoms-search-trends-inform-covid-19-research/) We are considering expanding to new countries. As we gather feedback, can you share the specific countries you had in mind and how you might use it?

**Comment by RoyalTS** [comment]
Was looking for Germany specifically, ideally at the level of "Landkreise" (~counties) and with German search terms instead of the English ones. Would gladly help translate those search terms if needed. As for use case, I was hoping to incorporate the data into a nowcasting/forecasting model.

**Comment by shekelto** [comment]
Hi Tobias,

Unfortunately we are unable to release the terms themselves in other language.
For Germany, if we will release the data, the resolution we are considering is the same one used in the Community Mobility Reports (www.google.com/covid19/mobility) which is one level more granular than the German states.
Thank you for highlighting the need in Germany, we will evaluate if that can be achieved.

**Comment by shekelto** [comment]
Hi there,

Wanted to update you that we just released data for Ireland, United Kingdom, New Zealand, Australia and Singapore.
