### ISSUE TITLE
Search Trends data is stale

### ISSUE THREAD

**Issue by krivard** [google-research/open-covid-19-data#190]
The Search Trends files include data that is tabulated weekly, but the last time the file was updated is over 16 days ago. Is this dataset intended to be continuously updated? If so, how frequently?

**Comment by shekelto** [comment]
Hi there,

Please see the recent update in the website. You should now have fresher data (available via our interactive charts webpage) in more countries.
Also weekly data is now available in many more regions. All details are in the relevant folder in this repo.

**Comment by krivard** [comment]
Thank you!
