### ISSUE TITLE
US only search trends data ?

### ISSUE THREAD

**Issue by perone** [google-research/open-covid-19-data#98]
Are there any plans to expand the dataset (of search trends) for other countries as well or it will be permanently US-only data ? Thanks !

**Comment by shekelto** [comment]
Hi there,

Thank you for your question.
As mentioned in our [blogpost](https://blog.google/technology/health/using-symptoms-search-trends-inform-covid-19-research/) this is an early release limited to the US.
As we receive feedback from public health researchers, civil society groups and the community at large, we’ll evaluate and expand this dataset by including additional countries and regions. So yes, there is an intent to expand beyond the US.

**Comment by shekelto** [comment]
Hi there,

Wanted to update you that we just expanded the dataset to include Ireland, New Zealand, Australia, United Kingdom and Singapore.
You can find more information about other improvements in the dataset documentation in this repository.
